Changes from 2010-01-07 to 2010-09-21.

diff --git a/contrib/util/restore b/contrib/util/restore
--- a/contrib/util/restore
+++ b/contrib/util/restore
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-# Copyright (C) 2008-2009 Rod Roark <rod@sunsetsystems.com>
+# Copyright (C) 2008-2010 Rod Roark <rod@sunsetsystems.com>
 #
 # This program is free software; you can redistribute it and/or
 # modify it under the terms of the GNU General Public License
@@ -172,18 +172,24 @@ if [ $? -ne 0 ]; then
   exit 1
 fi
 
+OEDIR=/var/www/openemr
+
+# Get the Site ID, it should be the only site backed up.
+SITEID=`ls -1 sites | head -n 1`
+
 # Get various parameters from the extracted files.
-OEDIR=`grep '^\$webserver_root' interface/globals.php | cut -d \" -f 2`
-OEDBNAME=`grep '^\$dbase' library/sqlconf.php | cut -d \' -f 2`
-OEDBUSER=`grep '^\$login' library/sqlconf.php | cut -d \' -f 2`
-OEDBPASS=`grep '^\$pass'  library/sqlconf.php | cut -d \' -f 2`
+OEDBNAME=`grep '^\$dbase' sites/$SITEID/sqlconf.php | cut -d \' -f 2 | cut -d \" -f 2`
+OEDBUSER=`grep '^\$login' sites/$SITEID/sqlconf.php | cut -d \' -f 2 | cut -d \" -f 2`
+OEDBPASS=`grep '^\$pass'  sites/$SITEID/sqlconf.php | cut -d \' -f 2 | cut -d \" -f 2`
 SLDBNAME=''
+# SL support is becoming obsolete, but we're leaving it in for now.
 if [ -f ../sql-ledger.sql ]; then
   SLDBNAME=`grep '^\$sl_dbname' interface/globals.php | cut -d \' -f 2`
   SLDBUSER=`grep '^\$sl_dbuser' interface/globals.php | cut -d \' -f 2`
   SLDBPASS=`grep '^\$sl_dbpass' interface/globals.php | cut -d \' -f 2`
 fi
-#
+# Likewise, external phpGACL is discouraged because it will not work
+# with multiple sites.
 GADIR=''
 GACONFIGDIR=''
 GADBNAME=''
@@ -222,13 +228,17 @@ if [ -f ../sql-ledger.tar.gz ]; then
   SLDIR=`dirname $OEDIR`/sql-ledger
 fi
 
-dlg_yesno 'Do you want to specify new locations and database names for the restore?'
+dlg_yesno "Do you want to specify site ID, locations or database names for the restore?"
+
 CHANGES=$RESULT
+OLDSITEID=$SITEID
 
 dlg_blank_line
 
 if [ $CHANGES -gt 0 ]; then
   dlg_msg "Current values are shown in [brackets]. Just hit Enter to leave them as-is."
+  dlg_input "Site ID [$SITEID]? "
+  if [ ! -z "$RESULT" ]; then SITEID="$RESULT"; fi
   dlg_input "OpenEMR database name [$OEDBNAME]? "
   if [ ! -z "$RESULT" ]; then OEDBNAME="$RESULT"; fi
   dlg_input "OpenEMR database user [$OEDBUSER]? "
@@ -263,40 +273,20 @@ if [ $CHANGES -gt 0 ]; then
     if [ ! -z "$RESULT" ]; then SLDBPASS="$RESULT"; fi
   fi
   OLDOEDIR="$OEDIR"
-  dlg_input "OpenEMR web directory [$OEDIR]? "
+  dlg_input "New OpenEMR web directory [$OEDIR]? "
   if [ ! -z "$RESULT" ]; then OEDIR="$RESULT"; fi
   if [ ! -z "$GADIR" ]; then
     OLDGADIR="$GADIR"
-    dlg_input "phpGACL web directory [$GADIR]? "
+    dlg_input "New phpGACL web directory [$GADIR]? "
     if [ ! -z "$RESULT" ]; then GADIR="$RESULT"; fi
   fi
   if [ ! -z "$SLDIR" ]; then
     OLDSLDIR="$SLDIR"
-    dlg_input "SQL-Ledger web directory [$SLDIR]? "
+    dlg_input "New SQL-Ledger web directory [$SLDIR]? "
     if [ ! -z "$RESULT" ]; then SLDIR="$RESULT"; fi
+    dlg_input "Previous SQL-Ledger web directory [$OLDSLDIR]? "
+    if [ ! -z "$RESULT" ]; then OLDSLDIR="$RESULT"; fi
   fi
-  #
-  # The following is to figure out the proper value for $web_root.
-  #
-  LOOKING=1
-  DOCROOT=`dirname $OEDIR`
-  OEFILE=`basename $OEDIR`
-  while [ $LOOKING -eq 1 ]; do
-    dlg_yesno "Is the Apache document root '$DOCROOT'?"
-    if [ $RESULT -eq 1 ]; then
-      LOOKING=0
-    else
-      OEFILE=`basename $DOCROOT`/$OEFILE
-      DOCROOT=`dirname $DOCROOT`
-      if [ "$DOCROOT" = "/" ]; then
-        LOOKING=0
-        OEFILE=`basename $OEDIR`
-        DOCROOT=`dirname $OEDIR`
-        dlg_msg "Never mind, I will assume '$DOCROOT'. You may need to manually correct" "the value of \$web_root in '$OEDIR/interface/globals.php'."
-      fi
-    fi
-  done
-  unset DOCROOT
   #
 fi
 
@@ -313,7 +303,7 @@ fi
 # same as for openemr.  This is to prevent screwups caused by persistent
 # database connections in PHP.
 if [ ! -z "$GADBNAME" ]; then
-  if [ "$GADBUSER" = "$SLDBUSER" ]; then
+  if [ "$GADBUSER" = "$OEDBUSER" ]; then
     dlg_msg "Error: OpenEMR and phpGACL have separate databases but the same user name." "They must be different user names."
     exit 1
   fi
@@ -356,6 +346,16 @@ if [ ! -z "$SLDIR" ]; then
   fi
 fi
 
+if [ -e "$OEDIR" -a ! -e "$OEDIR/sites" ]; then
+  dlg_msg "Error: Directory '$OEDIR/sites' is missing - old release needs removal?"
+  exit 1
+fi
+
+if [ -e "$OEDIR/sites/$SITEID" ]; then
+  dlg_msg "Error: Site '$SITEID' already exists in '$OEDIR/sites'."
+  exit 1
+fi
+
 COLLATE="utf8_general_ci"
 dlg_msg "If you have a particular requirement for the UTF-8 collation to use, " \
   "then please specify it here.  Hit Enter to accept the default '$COLLATE'." \
@@ -369,24 +369,27 @@ fi
 
 # Ask the user to do final sanity checking.
 #
-MARGS="\"I will restore the OpenEMR database backup to the MySQL database '$OEDBNAME'.\""
+MARGS="\"Your Site ID will be '$SITEID'.\""
+if [ -e "$OEDIR" ]; then
+  MARGS="$MARGS \"Only site-specific files will be restored to '$OEDIR/sites/$SITEID' in the existing OpenEMR web directory.\""
+else
+  MARGS="$MARGS \"I will install a new OpenEMR web directory '$OEDIR' from the backup.\""
+fi
+MARGS="$MARGS \"I will restore the OpenEMR database backup to the MySQL database '$OEDBNAME'.\""
 MARGS="$MARGS \"The OpenEMR database user will be '$OEDBUSER' with password '$OEDBPASS'.\""
 if [ ! -z "$GADBNAME" ]; then
   MARGS="$MARGS \"I will restore the phpGACL database backup to the MySQL database '$GADBNAME'.\""
   MARGS="$MARGS \"The phpGACL database user will be '$GADBUSER' with password '$GADBPASS'.\""
 fi
-
 if [ -z "$COLLATE" ]; then
   MARGS="$MARGS \"MySQL will use its default character set and collation.\""
 else
   MARGS="$MARGS \"MySQL will use character set 'utf8' with collation '$COLLATE'.\""
 fi
-
 if [ ! -z "$SLDBNAME" ]; then
   MARGS="$MARGS \"I will restore the SQL-Ledger database backup to the PostgreSQL database '$SLDBNAME'.\""
   MARGS="$MARGS \"The SQL-Ledger database user will be '$SLDBUSER' with password '$SLDBPASS'.\""
 fi
-MARGS="$MARGS \"I will copy the OpenEMR web directory backup to '$OEDIR'.\""
 if [ ! -z "$GADIR" ]; then
   MARGS="$MARGS \"I will copy the phpGACL web directory backup to '$GADIR'.\""
 fi
@@ -408,7 +411,7 @@ dlg_blank_line
 dlg_msg "In order to create MySQL databases and users on this computer, I will need to" \
         "log into MySQL as its 'root' user.  The next question asks for the MySQL root" \
         "user's password for this server, the one that you are restoring to.  This is"  \
-        "a MySQL password, not a system login password.  Often it is blank."
+        "a MySQL password, not a system login password.  It might be blank."
 dlg_input 'Enter the password, if any, for the MySQL root user:'
 MYROOTPASS="$RESULT"
 
@@ -522,43 +525,43 @@ if [ ! -z "$SLDBNAME" ]; then
   sudo -u postgres psql --command "ANALYZE" $SLDBNAME
 fi
 
-dlg_info "Restoring OpenEMR web directory tree ..."
-mkdir -p $OEDIR
-rm -rf $OEDIR
-mv $BAKDIR/openemr $OEDIR
-if [ $? -ne 0 ]; then
-  dlg_msg "Error: Cannot create directory '$OEDIR'."
-  exit 1
+if [ -e "$OEDIR" ]; then
+  dlg_info "Restoring site subdirectory ..."
+  mv $BAKDIR/openemr/sites/$OLDSITEID $OEDIR/sites/$SITEID
+  if [ $? -ne 0 ]; then
+    dlg_msg "Error: Cannot create directory '$OEDIR/sites/$SITEID'."
+    exit 1
+  fi
+else
+  dlg_info "Restoring OpenEMR web directory tree ..."
+  mv $BAKDIR/openemr $OEDIR
+  if [ $? -ne 0 ]; then
+    dlg_msg "Error: Cannot create directory '$OEDIR'."
+    exit 1
+  fi
 fi
 #
 if [ $CHANGES -gt 0 ]; then
-  dlg_info "Modifying $OEDIR/interface/globals.php ..."
-  cd $OEDIR/interface
-  mv -f globals.php globals.php.old
-  sed "s^$OLDOEDIR^$OEDIR^"                globals.php.old | \
-  sed "/\\\$web_root *=/ c \$web_root = \"/$OEFILE\";"     | \
-  sed "s^sl_dbname *= '.*'^sl_dbname = '$SLDBNAME'^"       | \
-  sed "s^sl_dbuser *= '.*'^sl_dbuser = '$SLDBUSER'^"       | \
-  sed "s^sl_dbpass *= '.*'^sl_dbpass = '$SLDBPASS'^"         \
-  > globals.php
-  #
-  dlg_info "Modifying $OEDIR/library/sqlconf.php ..."
-  cd $OEDIR/library
-  mv sqlconf.php sqlconf.php.old
-  sed "s^dbase\t= '.*'^dbase\t= '$OEDBNAME'^" sqlconf.php.old | \
-  sed "s^login\t= '.*'^login\t= '$OEDBUSER'^"                 | \
-  sed "s^pass\t= '.*'^pass\t= '$OEDBPASS'^" > sqlconf.php
-  #
-  dlg_info "Modifying $OEDIR/includes/config.php ..."
-  SLFILE=`dirname /$OEFILE`
-  if [ "$SLFILE" = "/" ]; then
-    SLFILE="/sql-ledger"
-  else
-    SLFILE="$SLFILE/sql-ledger"
+  if [ ! -z "$SLDIR" ]; then
+    dlg_info "Modifying $OEDIR/interface/globals.php ..."
+    cd $OEDIR/interface
+    mv -f globals.php globals.php.old
+    sed "s^sl_dbname *= '.*'^sl_dbname = '$SLDBNAME'^" globals.php.old | \
+    sed "s^sl_dbuser *= '.*'^sl_dbuser = '$SLDBUSER'^"                 | \
+    sed "s^sl_dbpass *= '.*'^sl_dbpass = '$SLDBPASS'^"                   \
+    > globals.php
   fi
-  cd $OEDIR/includes
-  cp -f config.php config.php.old
-  sed "s^\"/.*/ws_server.pl\"^\"$SLFILE/ws_server.pl\"^" config.php.old > config.php
+  #
+  dlg_info "Modifying $OEDIR/sites/$SITEID/sqlconf.php ..."
+  cd $OEDIR/sites/$SITEID
+  mv sqlconf.php sqlconf.php.old
+  sed "s^dbase\t= ['\"].*['\"]^dbase\t= '$OEDBNAME'^" sqlconf.php.old | \
+  sed "s^login\t= ['\"].*['\"]^login\t= '$OEDBUSER'^"                 | \
+  sed "s^pass\t= ['\"].*['\"]^pass\t= '$OEDBPASS'^" > sqlconf.php
+  #
+  # Logic to fix the path to ws_server.pl in includes/config.php was removed.
+  # Not gonna worry about this because SL is deprecated, the old logic was not
+  # very robust, and this can be fixed up manually easily enough.
 fi
 
 if [ ! -z "$GADIR" ]; then
@@ -575,17 +578,11 @@ if [ ! -z "$GADIR" ]; then
     dlg_info "Modifying $OEDIR/library/acl.inc ..."
     cd $OEDIR/library
     mv -f acl.inc acl.inc.old
-    sed "s^$OLDGADIR^$GADIR^" acl.inc.old > acl.inc
+    sed "s^phpgacl_location *= *\"/.*\"^phpgacl_location = \"$GADIR\"^" acl.inc.old > acl.inc
   fi
 fi
 
-if [ ! -z "$GACONFIGDIR" -a $CHANGES -gt 0 ]; then
-  if [ -z "$GADBNAME" ]; then
-    GADBNAME="$OEDBNAME"
-    GADBUSER="$OEDBUSER"
-    GADBPASS="$OEDBPASS"
-  fi
-  #
+if [ ! -z "$GACONFIGDIR" -a $CHANGES -gt 0 -a ! -z "$GADBNAME" ]; then
   dlg_info "Modifying $GACONFIGDIR/gacl.class.php ..."
   cd $GACONFIGDIR
   mv -f gacl.class.php gacl.class.php.old
